### ISSUE TITLE
Windows open at smoke alarm?

### ISSUE THREAD

**Issue by pz1** [maros/Zway-WindowControl#1]
The readme says:
>  In case of a smoke alarm all windows managed by the controller are automatically opened.

Opening windows in such a situation may not be a good idea. It does allow more oxygen to enter the building. That often leads bursts of flames.

**Comment by maros** [comment]
Oh, that README stems form an old dev version, and the code itself was never released. Should have deleted the paragraph. 
Not sure if opening windows in case of a smoke alarm is a good thing or not, though. Most of injuries/deaths associated with fire/smoke are not from the fire itself but from smoke inhalations. I was thinking about opening the windows only when there is somebody at home. What do you think?

**Comment by pz1** [comment]
I am not at all a specialist in this area.
I know many office buildings where normally open doors, do close at fire alarm just to prevent drafts in the corridors.  I have seen fires intensify after windows on the ground floor broke. Hot smoke inhalations seem best prevented by using wet towels at nose and mouth, while moving as close as possible to the floor.

If a building is filled with smoke, but there is no (longer) a fire, ventilation may be more appropriate.

PS: I accidentally came across this issue when I looked into the readme to see if it would also control heaters on window opening as requested by this [post on the forum](http://forum.z-wave.me/viewtopic.php?f=3419&t=24004&p=64875#p64875)

**Comment by pz1** [comment]
Feel free to close this comment if you feel it is no longer relevant

**Comment by maros** [comment]
See dd4254ee84d39d3ee94d385b908a7167c2d5fad8
